server:
  port: 8140 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tFKwSnzjPKw3BA4b6BZ
    keySecret: N7v6R4V3EJ1SGDZlsqtqo8QyVVMmtQ
    bucketName: 2022-01-13
