server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务地址

aliyun:
  oss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    keyId: LTAI5tFKwSnzjPKw3BA4b6BZ
    keySecret: KX87c8fYGFYsXEIW2YtR5FVgx3ANQ6
    bucketName: 2022-01-13


#设置日志级别
#logging:
#  level:
#    root: error
logging:
  level:
    com.yang.srb.core.mapper: debug
  pattern:
    level: DEBUG
